#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["src/Service/Customer/Customer.Api/Customer.Api/Customer.Api.csproj", "src/Service/Customer/Customer.Api/Customer.Api/"]
RUN dotnet restore "src/Service/Customer/Customer.Api/Customer.Api/Customer.Api.csproj"
COPY . .
WORKDIR "/src/src/Service/Customer/Customer.Api/Customer.Api"
RUN dotnet build "Customer.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Customer.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Customer.Api.dll"]