// <auto-generated />
using Customer.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customer.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210711232502_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Customer")
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Customer.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "Name for Client 1"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "Name for Client 2"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "Name for Client 3"
                        },
                        new
                        {
                            ClientId = 4,
                            Name = "Name for Client 4"
                        },
                        new
                        {
                            ClientId = 5,
                            Name = "Name for Client 5"
                        },
                        new
                        {
                            ClientId = 6,
                            Name = "Name for Client 6"
                        },
                        new
                        {
                            ClientId = 7,
                            Name = "Name for Client 7"
                        },
                        new
                        {
                            ClientId = 8,
                            Name = "Name for Client 8"
                        },
                        new
                        {
                            ClientId = 9,
                            Name = "Name for Client 9"
                        },
                        new
                        {
                            ClientId = 10,
                            Name = "Name for Client 10"
                        },
                        new
                        {
                            ClientId = 11,
                            Name = "Name for Client 11"
                        },
                        new
                        {
                            ClientId = 12,
                            Name = "Name for Client 12"
                        },
                        new
                        {
                            ClientId = 13,
                            Name = "Name for Client 13"
                        },
                        new
                        {
                            ClientId = 14,
                            Name = "Name for Client 14"
                        },
                        new
                        {
                            ClientId = 15,
                            Name = "Name for Client 15"
                        },
                        new
                        {
                            ClientId = 16,
                            Name = "Name for Client 16"
                        },
                        new
                        {
                            ClientId = 17,
                            Name = "Name for Client 17"
                        },
                        new
                        {
                            ClientId = 18,
                            Name = "Name for Client 18"
                        },
                        new
                        {
                            ClientId = 19,
                            Name = "Name for Client 19"
                        },
                        new
                        {
                            ClientId = 20,
                            Name = "Name for Client 20"
                        },
                        new
                        {
                            ClientId = 21,
                            Name = "Name for Client 21"
                        },
                        new
                        {
                            ClientId = 22,
                            Name = "Name for Client 22"
                        },
                        new
                        {
                            ClientId = 23,
                            Name = "Name for Client 23"
                        },
                        new
                        {
                            ClientId = 24,
                            Name = "Name for Client 24"
                        },
                        new
                        {
                            ClientId = 25,
                            Name = "Name for Client 25"
                        },
                        new
                        {
                            ClientId = 26,
                            Name = "Name for Client 26"
                        },
                        new
                        {
                            ClientId = 27,
                            Name = "Name for Client 27"
                        },
                        new
                        {
                            ClientId = 28,
                            Name = "Name for Client 28"
                        },
                        new
                        {
                            ClientId = 29,
                            Name = "Name for Client 29"
                        },
                        new
                        {
                            ClientId = 30,
                            Name = "Name for Client 30"
                        },
                        new
                        {
                            ClientId = 31,
                            Name = "Name for Client 31"
                        },
                        new
                        {
                            ClientId = 32,
                            Name = "Name for Client 32"
                        },
                        new
                        {
                            ClientId = 33,
                            Name = "Name for Client 33"
                        },
                        new
                        {
                            ClientId = 34,
                            Name = "Name for Client 34"
                        },
                        new
                        {
                            ClientId = 35,
                            Name = "Name for Client 35"
                        },
                        new
                        {
                            ClientId = 36,
                            Name = "Name for Client 36"
                        },
                        new
                        {
                            ClientId = 37,
                            Name = "Name for Client 37"
                        },
                        new
                        {
                            ClientId = 38,
                            Name = "Name for Client 38"
                        },
                        new
                        {
                            ClientId = 39,
                            Name = "Name for Client 39"
                        },
                        new
                        {
                            ClientId = 40,
                            Name = "Name for Client 40"
                        },
                        new
                        {
                            ClientId = 41,
                            Name = "Name for Client 41"
                        },
                        new
                        {
                            ClientId = 42,
                            Name = "Name for Client 42"
                        },
                        new
                        {
                            ClientId = 43,
                            Name = "Name for Client 43"
                        },
                        new
                        {
                            ClientId = 44,
                            Name = "Name for Client 44"
                        },
                        new
                        {
                            ClientId = 45,
                            Name = "Name for Client 45"
                        },
                        new
                        {
                            ClientId = 46,
                            Name = "Name for Client 46"
                        },
                        new
                        {
                            ClientId = 47,
                            Name = "Name for Client 47"
                        },
                        new
                        {
                            ClientId = 48,
                            Name = "Name for Client 48"
                        },
                        new
                        {
                            ClientId = 49,
                            Name = "Name for Client 49"
                        },
                        new
                        {
                            ClientId = 50,
                            Name = "Name for Client 50"
                        },
                        new
                        {
                            ClientId = 51,
                            Name = "Name for Client 51"
                        },
                        new
                        {
                            ClientId = 52,
                            Name = "Name for Client 52"
                        },
                        new
                        {
                            ClientId = 53,
                            Name = "Name for Client 53"
                        },
                        new
                        {
                            ClientId = 54,
                            Name = "Name for Client 54"
                        },
                        new
                        {
                            ClientId = 55,
                            Name = "Name for Client 55"
                        },
                        new
                        {
                            ClientId = 56,
                            Name = "Name for Client 56"
                        },
                        new
                        {
                            ClientId = 57,
                            Name = "Name for Client 57"
                        },
                        new
                        {
                            ClientId = 58,
                            Name = "Name for Client 58"
                        },
                        new
                        {
                            ClientId = 59,
                            Name = "Name for Client 59"
                        },
                        new
                        {
                            ClientId = 60,
                            Name = "Name for Client 60"
                        },
                        new
                        {
                            ClientId = 61,
                            Name = "Name for Client 61"
                        },
                        new
                        {
                            ClientId = 62,
                            Name = "Name for Client 62"
                        },
                        new
                        {
                            ClientId = 63,
                            Name = "Name for Client 63"
                        },
                        new
                        {
                            ClientId = 64,
                            Name = "Name for Client 64"
                        },
                        new
                        {
                            ClientId = 65,
                            Name = "Name for Client 65"
                        },
                        new
                        {
                            ClientId = 66,
                            Name = "Name for Client 66"
                        },
                        new
                        {
                            ClientId = 67,
                            Name = "Name for Client 67"
                        },
                        new
                        {
                            ClientId = 68,
                            Name = "Name for Client 68"
                        },
                        new
                        {
                            ClientId = 69,
                            Name = "Name for Client 69"
                        },
                        new
                        {
                            ClientId = 70,
                            Name = "Name for Client 70"
                        },
                        new
                        {
                            ClientId = 71,
                            Name = "Name for Client 71"
                        },
                        new
                        {
                            ClientId = 72,
                            Name = "Name for Client 72"
                        },
                        new
                        {
                            ClientId = 73,
                            Name = "Name for Client 73"
                        },
                        new
                        {
                            ClientId = 74,
                            Name = "Name for Client 74"
                        },
                        new
                        {
                            ClientId = 75,
                            Name = "Name for Client 75"
                        },
                        new
                        {
                            ClientId = 76,
                            Name = "Name for Client 76"
                        },
                        new
                        {
                            ClientId = 77,
                            Name = "Name for Client 77"
                        },
                        new
                        {
                            ClientId = 78,
                            Name = "Name for Client 78"
                        },
                        new
                        {
                            ClientId = 79,
                            Name = "Name for Client 79"
                        },
                        new
                        {
                            ClientId = 80,
                            Name = "Name for Client 80"
                        },
                        new
                        {
                            ClientId = 81,
                            Name = "Name for Client 81"
                        },
                        new
                        {
                            ClientId = 82,
                            Name = "Name for Client 82"
                        },
                        new
                        {
                            ClientId = 83,
                            Name = "Name for Client 83"
                        },
                        new
                        {
                            ClientId = 84,
                            Name = "Name for Client 84"
                        },
                        new
                        {
                            ClientId = 85,
                            Name = "Name for Client 85"
                        },
                        new
                        {
                            ClientId = 86,
                            Name = "Name for Client 86"
                        },
                        new
                        {
                            ClientId = 87,
                            Name = "Name for Client 87"
                        },
                        new
                        {
                            ClientId = 88,
                            Name = "Name for Client 88"
                        },
                        new
                        {
                            ClientId = 89,
                            Name = "Name for Client 89"
                        },
                        new
                        {
                            ClientId = 90,
                            Name = "Name for Client 90"
                        },
                        new
                        {
                            ClientId = 91,
                            Name = "Name for Client 91"
                        },
                        new
                        {
                            ClientId = 92,
                            Name = "Name for Client 92"
                        },
                        new
                        {
                            ClientId = 93,
                            Name = "Name for Client 93"
                        },
                        new
                        {
                            ClientId = 94,
                            Name = "Name for Client 94"
                        },
                        new
                        {
                            ClientId = 95,
                            Name = "Name for Client 95"
                        },
                        new
                        {
                            ClientId = 96,
                            Name = "Name for Client 96"
                        },
                        new
                        {
                            ClientId = 97,
                            Name = "Name for Client 97"
                        },
                        new
                        {
                            ClientId = 98,
                            Name = "Name for Client 98"
                        },
                        new
                        {
                            ClientId = 99,
                            Name = "Name for Client 99"
                        },
                        new
                        {
                            ClientId = 100,
                            Name = "Name for Client 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
